### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by mpdude** [RideAmigosCorp/ec2-consistent-snapshot.sh#1]
@markstos are you still actively using this, possibly supporting the use and accepting PRs?

**Comment by markstos** [comment]
I am not actively using this. It's my latest understanding that the software I'm using is "crash-consistent". That is, it can be restored to a consistent state after a crash, which is essentially the state achieved by taking AWS snapshots without running this tool.

I can transfer this repo to your ownership if you'd like.

**Comment by mpdude** [comment]
Unfortunately, I still have to support MySQL with MyISAM tables, which (to my understanding) are _not_ crash-consistent. 

So, thank you for the generous offer. However, having an open MySQL connection in the background to flush and lock tables _before_ proceeding turned out to be non-trivial in `bash`. So I ended up writing up "the most simple thing that could possibly work" in PHP which I am more familiar with.

Again, thanks for your offer!
